---
- name: Install and configure various softwares on Ubuntu hosts
  hosts: server_ubuntu
  #when: ansible_os_family == "Debian" and ansible_fqdn != "msi"

  tasks:
  - name: Validate host name
    ansible.builtin.debug:
      msg: working on host {{ ansible_fqdn }}

  - name: Install multiple apps
    ansible.builtin.apt:
      pkg:
        - guake
        - timeshift
        - openssh-client
        - openssh-server
        - gnome-software
        - tldr
        - numlockx
        - git
        - vscode
        - vscode-insiders
        - azuredatastudio
        - python
        - python-is-python3
        - jupyterlab
        - slack
        - flameshot
        - samba
        - smbclient
        - caja-share
        - nginx
        - simplescreenrecorder
        - qbittorrent
        - guvcview
        - vlc
        - Stacer
        - cpu-x
        - cockpit
        - podman
        - cockpit-podman
        - cockpit-machines
        - netstat
        - zoom
        - kdiskmark
        - remmina
        - htop
        - mssql-cli
        - ffmpeg
        - xrdp
        - 7zip
        - ubuntu-restricted-extras
      state: latest
      update_cache: true
      register: apt_result
      #failed_when: apt_result.rc != 0 and "some_specific_error" not in apt_result.stderr
    ignore_errors: true

  - name: Install games
    ansible.builtin.apt:
      pkg:
        - supertux
        - tuxmath
        - supertuxkart
        - gimp
        - notepadqq
        - scratch
        - gparted
        - scratchjr
        - gcompris
        - kolibri
        - klettres
        - kolourpaint
      state: latest
      update_cache: true

  - name: Configure services
    ansible.builtin.service:
      name:
        - ssh
        - smbd
        - nginx
        - cockpit
        - podman
      enabled: true
      state: started

  - name: Add firewall exceptions by profile
    community.general.ufw:
      name:
        - openssh-server
        - Samba
        - nginx
        - cockpit
      rule: allow
      state: enabled

  - name: Install ubuntu-mate-desktop
    ansible.builtin.apt:
      pkg:
        - ubuntu-mate-desktop
    when: ansible_fqdn != "msi"

  - name: Fix missing dependencies
    ansible.builtin.shell:
      cmd: apt install -f
