---
- name: Replace lines in a file
  hosts: all
  become: yes
  vars:
    file_path: "/etc/pgbackrest/pgbackrest.conf"
    new_repo1_key: "SOME$WEIRD$AWS$KEY"
    new_repo1_secret: "I$REALLY$DONT$KNOW$ANY$WEIRD$AWS$KEY"
  tasks:
    - name: Replace AWS S3 bucket key
      ansible.builtin.lineinfile:
        path: "{{ file_path }}"
        regexp: "^repo1-s3-key\\s*=.*"
        line: "repo1-s3-key={{ new_repo1_key }}"
        backrefs: yes
    - name: Replace AWS S3 bucket key
      ansible.builtin.lineinfile:
        path: "{{ file_path }}"
        regexp: "^repo1-s3-key-secret\\s*=.*"
        line: "repo1-s3-key-secret={{ new_repo1_secret }}"
        backrefs: yes