---
- name: Configure /etc/hosts using jinja2 template
  hosts: ansible_vms
  tasks:
    - name: show templating results
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.template', './configure_etc_hosts.j2', comment_start_string='##', comment_end_string='##]') }}"

    - name: Remove file if exists
      ansible.builtin.file:
        path: /tmp/etc_hosts
        state: absent

    - name: Create file if not exists
      ansible.builtin.file:
        path: /tmp/etc_hosts
        state: touch

    # - name: Configure /etc/hosts
    #   ansible.builtin.template:
    #     src: configure_etc_hosts.j2
    #     dest: /tmp/etc_hosts

    - name: Update /etc/hosts
      ansible.builtin.blockinfile:
        path: /tmp/etc_hosts
        #insertafter: "defaults"
        marker: "##<!-- {mark} ANSIBLE MANAGED BLOCK -->##"
        block: |
          {{ lookup('ansible.builtin.template', './configure_etc_hosts.j2', comment_start_string='##', comment_end_string='##]') }}

# ansible-playbook ansible-core-concepts/managing-files/configure_etc_hosts.yml
# ansible ansible_vms -a 'cat /tmp/etc_hosts'
