---
- name: file copy modules
  hosts: ansible_vms
  tasks:
    - name: copy file demo
      ansible.builtin.copy:
        src: /etc/hosts
        dest: /tmp/
    - name: add some lines to /tmp/hosts
      ansible.builtin.blockinfile:
        path: /tmp/hosts
        block: |
          192.168.4.110 host1.example.com
          192.168.4.120 host2.example.com
        state: present
    - name: verify file checksum
      ansible.builtin.stat:
        path: /tmp/hosts
        checksum_algorithm: md5
      register: result
    - name: print result message
      ansible.builtin.debug:
        msg: "The checksum of /tmp/hosts is {{ result.stat.checksum }}"
    - name: fetch a file
      ansible.builtin.fetch:
        src: /tmp/hosts
        dest: /tmp/

# ansible-playbook ansible-core-concepts/managing-files/copy.yml
