---
- name: Generate postgres user password
  hosts: all
  # become: yes
  gather_facts: false
  remote_user: ansible
  vars_files:
    - sensitive_values
  vars:
    db_user_rw: "facebook_prod_rw"
    db_user_ro: "facebook_prod_ro"
    pwd_length: 15
    # pagerduty_integration_key: "{{ lookup('env', 'PAGERDUTY_INTEGRATION_KEY') }}"
    pagerduty_integration_key: "{{ PAGERDUTY_PGDBA_INTEGRATION_KEY }}"
    # slack_token: "{{ lookup('env', 'SLACK_DBA_BOT_OAUTH_TOKEN') }}"
    slack_token: "{{ SLACK_DBA_BOT_OAUTH_TOKEN }}"
    # slack_channel: "{{ lookup('env', 'SLACK_DBA_CHANNEL_NAME') }}"
    slack_channel: "{{ SLACK_DBA_CHANNEL_NAME }}"
    # slack_channel_id: "{{ lookup('env', 'SLACK_DBA_CHANNEL_ID') }}"
    slack_channel_id: "{{ SLACK_DBA_CHANNEL_ID }}"
    slack_thread_header: '*PostgreSQL User Password Details*'
    dba_slack_users:
      - U034U24K6TF

  tasks:

    - name: Generate random postgres user password
      ansible.builtin.set_fact:
        db_user_rw_password: "{{ lookup('password', '/dev/null', length=pwd_length, chars='ascii_letters,digits') }}"
        db_user_ro_password: "{{ lookup('password', '/dev/null', length=pwd_length, chars='ascii_letters,digits') }}"

    - name: Print generated password
      ansible.builtin.debug:
        msg: >
          db_user_rw: {{ db_user_rw }} || db_user_rw_password: '{{ db_user_rw_password }}'
          db_user_ro: {{ db_user_ro }} || db_user_ro_password: '{{ db_user_ro_password }}'

    - name: Debug slack_token
      ansible.builtin.debug:
        var: slack_token

    - name: Debug variables
      ansible.builtin.debug:
        # msg: "{{ item }}: {{ hostvars[inventory_hostname][item] }}"
        msg: "{{ item }}: {{ lookup('vars', item) | default('NOT SET') }}"
      loop:
        - slack_token
        - slack_channel
        - slack_channel_id
        - pagerduty_integration_key

    - name: Send a direct message to a Slack user
      ansible.builtin.uri:
        url: https://slack.com/api/chat.postMessage
        method: POST
        headers:
          Authorization: "Bearer {{ slack_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          channel: "{{ item }}"
          text: "{{ slack_thread_header }}"
      delegate_to: localhost
      loop: "{{ dba_slack_users }}"

