---
- name: Playbook to send PagerDuty Alert
  hosts: localhost
  become_user: root
  remote_user: ansible
  # become: true
  gather_facts: false
  vars:
    # pagerduty_integration_key: "{{ PAGERDUTY_INTEGRATION_KEY }}"
    pagerduty_integration_key: "{{ lookup('env', 'PAGERDUTY_INTEGRATION_KEY') }}"  # or hardcode token here
  tasks:
    - name: Trigger PagerDuty Alert for UnHealthy State
      vars:
            # cluster_dict: "{{ item | join('\n') | from_yaml }}"
            cluster_name: "FFPTRM-CUG-CLUSTER"
            # cluster_leader_host: ""
            # cluster_host_01: "{{ cluster_dict[0] }}"
            # cluster_host_02: "{{ cluster_dict[1] }}"
            # cluster_host_03: "{{ cluster_dict[2] }}"
            # has_role_issue: >-
            #   {{ cluster_host_01.Role not in good_roles or cluster_host_02.Role not in good_roles or cluster_host_03.Role not in good_roles }}
            # has_state_issue: >-
            #   {{ cluster_host_01.State not in good_states or cluster_host_02.State not in good_states or cluster_host_03.State not in good_states }}
      community.general.pagerduty_alert:
        integration_key: "{{ pagerduty_integration_key }}"
        api_version: v2
        source: Github Workflow [Check Cluster State]
        state: triggered
        desc: |
          Patroni Cluster [{{ cluster_name }}] in UnHealthy State
        incident_key: "{{ cluster_name }}"
        client: PostgreSQL Ansible Alert
        client_url: https://ajaydwivedi.pagerduty.com/service-directory/PTGZFDD/activity
        component: patronictl
        incident_class: patroni cluster issue
        link_url: https://ajaydwivedi.pagerduty.com/service-directory/PTGZFDD/activity
        link_text: Active PagerDuty Alerts
      # when:
      #   - has_role_issue or has_state_issue
      #   - clusters_to_ignore is not defined or cluster_name not in clusters_to_ignore
      # loop: "{{ cluster_list }}"

# cd ansible-core-concepts/slack-pagerduty-alert
# export PAGERDUTY_INTEGRATION_KEY=<YouPagerDutyIntegrationKey>
# ansible-playbook -i hosts.yml trigger-pagerduty-alert.yml