---
# - name: Update OS
#   hosts: server_desktop
#   tasks:
- name: Get latest release of balena-etcher
  ansible.builtin.uri:
    url: "https://api.github.com/repos/balena-io/etcher/releases/latest"
    return_content: yes
  register: etcher_release

- name: Set facts for balena-etcher
  ansible.builtin.set_fact:
    repo_release: "{{ etcher_release.json.tag_name }}"
    repo_release_version: "{{ etcher_release.json.tag_name | regex_replace('^v', '') }}"
    deb_package: "balena-etcher_{{etcher_release.json.tag_name | regex_replace('^v', '')}}_amd64.deb"

- name: Download balena-etcher
  ansible.builtin.get_url:
    url: "https://github.com/balena-io/etcher/releases/download/{{repo_release}}/{{deb_package}}"
    dest: "/tmp/{{deb_package}}"
    mode: "0644"

- name: Install balena-etcher
  ansible.builtin.apt:
    deb: "/tmp/{{deb_package}}"
