---
- name: Access non apt packages
  ansible.builtin.debug:
    msg: "Install => {{ non_packaged_softwares | map(attribute='friendly_name') | join(', ') }}"

- name: Download non apt packages
  ansible.builtin.get_url:
    url: "{{ deb_software.url }}"
    dest: "/tmp/{{ deb_software.name }}.deb"
    mode: "0644"
  loop: "{{ non_packaged_softwares }}"
  loop_control:
    loop_var: deb_software

- name: Install non apt packages
  ansible.builtin.apt:
    deb: "/tmp/{{ deb_software.name }}.deb"
  loop: "{{ non_packaged_softwares }}"
  loop_control:
    loop_var: deb_software
