---
# tasks file for core-packages

- name: Print role name
  debug:
    msg: "Running [{{ role_name }}] role"

- name: Update OS cache
  ignore_errors: true
  import_tasks: tasks/update-os.yml

- name: Install core packages
  ignore_errors: true
  include_tasks: "{{ package_file }}"
  loop:
    - tasks/install-core-packages.yml
    - tasks/install-softwares-packages.yml
    - tasks/install-learnings-packages.yml
    - tasks/install-games-packages.yml
    - tasks/install-balena-etcher.yml
    # - tasks/install-anaconda.yml
    - tasks/install-brave-browser.yml
    # - tasks/install-chatgpt-desktop.yml
    # - tasks/install-powershell-core.yml
    - tasks/install-non_packaged_softwares.yml

  loop_control:
    loop_var: package_file

- name: Remove unwanted packages
  ignore_errors: true
  import_tasks: tasks/remove-packages.yml

- name: Install missing dependencies
  ignore_errors: true
  ansible.builtin.shell:
    cmd: apt-get install -f

