---
- name: Update OS
  hosts: server_desktop
  vars_files:
    - ../../../vars/desktop_vars.yml
  tasks:
  - name: Download GCompris Shell Script
    become_user: "{{ customize_user }}"
    ansible.builtin.get_url:
      #url: "https://download.kde.org/stable/gcompris/qt/linux/gcompris-qt-25.0-Linux64.sh"
      url: "https://ftp.fau.de/kde/stable/gcompris/qt/linux/gcompris-qt-25.0-Linux64.sh"
      dest: "/tmp/gcompris-qt-25.0-Linux64.sh"
      mode: "0755"

  - name: Install GCompris from Shell Script
    become_user: "{{ customize_user }}"
    ansible.builtin.shell: /tmp/gcompris-qt-25.0-Linux64.sh
