---
# - name: Update OS
#   hosts: server_desktop
#   tasks:
- name: Get latest release of chatgpt-desktop
  ansible.builtin.uri:
    url: "https://api.github.com/repos/lencx/ChatGPT/releases/latest"
    return_content: yes
  register: chatgpt_release

- name: Set facts for chatgpt-desktop
  ansible.builtin.set_fact:
    repo_release: "{{ chatgpt_release.json.tag_name }}"
    repo_release_version: "{{ chatgpt_release.json.tag_name | regex_replace('^v', '') }}"
    deb_package: "ChatGPT_{{chatgpt_release.json.tag_name | regex_replace('^v', '')}}_linux_x86_64.deb"

- name: Download chatgpt-desktop
  ansible.builtin.get_url:
    url: "https://github.com/lencx/ChatGPT/releases/download/{{repo_release}}/{{deb_package}}"
    dest: "/tmp/{{deb_package}}"
    mode: "0644"

- name: Install chatgpt-desktop dependencies repo
  ansible.builtin.blockinfile:
    path: /etc/apt/sources.list.d/ubuntu.sources
    #marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    prepend_newline: yes
    block: |
      Types: deb
      URIs: http://gb.archive.ubuntu.com/ubuntu
      Suites: jammy
      Components: main

- name: Update APT package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install chatgpt-desktop dependencies
  ansible.builtin.apt:
    name: libwebkit2gtk-4.0-dev
    #state: latest
    state: present

- name: Install chatgpt-desktop
  ansible.builtin.apt:
    deb: "/tmp/{{deb_package}}"
