---
- name: Demonstrating the POC role
  hosts: localhost
  vars:
    ansible_manager: Saanvi
    playbook_base_dir_name: "{{ playbook_dir | basename }}"

  pre_tasks:
    - name: Get playbook base directory name
      ansible.builtin.set_fact:
        playbook_base_dir_name: "{{ playbook_dir | basename }}"
    - name: Show the base directory name
      ansible.builtin.debug:
        msg: "The playbook base directory is: {{ playbook_base_dir_name }}"

  # roles:
  #   - poc-role

  tasks:
    - name: Execute role {{playbook_base_dir_name}}
      ansible.builtin.include_role:
        name: "../{{ playbook_base_dir_name }}"