all:
  children:
    linux:
      children:
        rhel:
          hosts:
            # ansible-centos:
            # ansible-fedora:
              # ansible_python_interpreter: /usr/libexec/platform-python
            # ansible-rhel:
          vars:
            # ansible_python_interpreter: /usr/bin/python3.12
        debian:
          children:
            server:
              hosts:
                # ansible-ubuntu-server:
                # ansible-git-01:
                # ansible-git-02:
                # ansible-ubuntu-postgres:
                # pg-cls1-prod0:
                # pg-cls1-prod1:
                # pg-cls1-prod2:
                # pg-cls1-dr0:
                # pg-cls1-dr1:
                # pg-cls1-dr2:
                # pg-pub:
                # pg-sub:
            desktop:
              hosts:
                # pgpoc:
                pgpractice:
                # ansible-ubuntu-desktop:
    windows:
      children:
        desktop:
          hosts:
            # sqlpractice:
        server:
          hosts:
            # demo:

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

# Discover python path
  # ansible rhel -i hosts.yml -m command -a "which python3"