all:
  children:
    linux:
      children:
        redhat:
          children:
            server_redhat:
              hosts:
                pg-pub2:
                pg-sub2:
            desktop_redhat:
              hosts:
                # ansible-centos:
                # ansible-fedora:
                #   ansible_python_interpreter: /usr/libexec/platform-python
                # ansible-rhel:
          vars:
            # ansible_python_interpreter: /usr/bin/python3.12
        debian:
          children:
            server_debian:
              hosts:
                # ansible-ubuntu-server:
                # ansible-git-01:
                # ansible-git-02:
                # ansible-ubuntu-postgres:
                # pg-cls1-prod0:
                # pg-cls1-prod1:
                # pg-cls1-prod2:
                # pg-cls1-dr0:
                # pg-cls1-dr1:
                # pg-cls1-dr2:
                # pg-pub:
                # pg-sub:
            desktop_debian:
              hosts:
                # pgpoc:
                # pgpractice:
                # phantom:
                # ansible-ubuntu-desktop:
    windows:
      children:
        desktop_windows:
          hosts:
            # sqlpractice:
        server_windows:
          hosts:
            # demo:

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

# Discover python path
  # ansible rhel -i hosts.yml -m command -a "which python3"
# ansible-inventory -i hosts.yml --list
# ansible-inventory -i hosts.yml --graph
# ansible all -i hosts.yml -m setup -a 'filter=ansible_os_family'
