- name: Configure VMs
  hosts: all
  become: true
  remote_user: ansible
  become_user: root
  gather_facts: true
  any_errors_fatal: true
  vars_files:
    - sensitive_values

  roles:
    - role: join_linux_to_ad
    # - role: ubuntu-setup-config
    # - role: "{{ role_name }}"
      vars:
        minimal_ansible_version: 2.11.0

# pwd
  # /home/saanvi/GitHub/Ansible-Learning/lab-setup-roles
# |------------$ tree -L 1
  # ├── hosts.yml
  # ├── join_linux_to_ad
  # ├── sensitive_values
  # ├── site.yml
  # └── vault-pass
# ansible-playbook -i hosts.yml site.yml --vault-password-file=../vault-pass
