---
- name: Using "assert" to decide if file should be created or not
  hosts: localhost
  vars_prompt:
  - name: filesize
    prompt: "specify a file size in mb"
  tasks:
  - name: Print filesize provided
    ansible.builtin.debug:
      msg: filesize is {{ filesize }} mb
  - name: check if file size is valid
    assert:
      that:
        - filesize | int <= 100
        - filesize | int >= 1
      fail_msg: "file size must be between 0 and 100"
      success_msg: "file size is good, lets continue"
  - name: create a file
    command: dd if=/dev/zero of=/bigfile bs=1 count={{ filesize }}

# ansible-playbook ansible-core-concepts/using-conditionals/assertsize-wrong.yml

