---
- name: demo how register works
  hosts: ansible_vms
  vars:
    username: anna
  tasks:
    - name: show register on random module
      ansible.builtin.user:
        name: "{{ username }}"
      register: user
    - name: show register results
      ansible.builtin.debug:
        var: user

# ansible-playbook ansible-core-concepts/using-conditionals/register.yml

