all:
  children:
    vms:
      hosts:
        ansible-git-02:

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    become: true
    ansible_user: saanvi

# ssh-copy-id ansible-git-02
# cd ansible-core-concepts/setup-ansible-hosts
# ansible -i hosts.yml all -m ping
# ansible -i hosts.yml all -k -b -K -m command -a "adduser ansible"
# ansible -i hosts.yml all -K -m shell -a "echo 'ansible:ansible' | sudo chpasswd"
