---
- name: showing map
  hosts: server_ansible
  gather_facts: no
  ignore_errors: true
  vars:
    basedir: /var/www/html
  tasks:
  - name: install httpd
    dnf:
      name: httpd
      state: latest
  - name: showing files in basedir
    find:
      paths: "{{ basedir }}"
      recurse: yes
    register: basedir_files
  - name: showing current variable contents to understand why we need map
    debug:
      var: basedir_files
  - name: show files based on map attribute with list
    set_fact:
      webfileslist: "{{ basedir_files['files'] | map(attribute='path') | list }}"
  - debug:
      var: webfileslist
  - name: now that we know that the list filter is mandatory, show relative file name
    set_fact:
      webfilesrelative: "{{ webfileslist | map('relpath', basedir) | list }}"
  - debug:
      var: webfilesrelative

# ansible server_ansible -m shell -a 'touch /var/www/html/{one,two,three}'
# ansible server_ansible -a 'mkdir /var/www/html/alerts'
# ansible server_ansible -a 'touch /var/www/html/alerts/cpu'
# ansible-playbook ansible-core-concepts/using-filters/filemap.yaml

