---
- name: create user with encrypted pass
  hosts: server_ansible
  vars_prompt:
  - name: passw
    prompt: which password do you want to use
  vars:
    user: sharon
  tasks:
  - debug:
      msg: "{{ '{{ passw }}' | password_hash('sha512','myrandomsalt') }}"
    register: mypass
  - debug:
      var: mypass
  - name: create the user
    user:
      name: "{{ user }}"
      password: "{{ mypass.msg }}"

# ansible-playbook ansible-core-concepts/using-filters/password_hash.yaml
# ansible server_ansible -m user -a "name=sharon state=absent"
