---
# tasks file for ubuntu-mate-desktop
- name: Print role name
  debug:
    msg: "Running [{{ role_name }}] role"

- name: Install [psutil] python package
  ansible.builtin.shell:
    cmd: pip3 install psutil --break-system-packages
  tags: [install, config]

- name: Copy [dconf-org_mate.ini] to {{ ansible_host}}
  become_user: "{{ customize_user }}"
  become: true
  ansible.builtin.copy:
    src: "{{role_path}}/files/dconf-org_mate.ini"
    dest: /tmp/dconf-org_mate.ini
    mode: '0644'
  tags: [install, config]

- name: Set panel [default-layout] in MATE tweak
  become_user: "{{ customize_user }}"
  become: true
  community.general.dconf:
    key: "/org/mate/panel/general/default-layout"
    value: "'redmond'"

- name: Apply MATE settings from config file
  become_user: "{{ customize_user }}"
  become: true
  ansible.builtin.shell:
    cmd: dbus-launch dconf load /org/mate/ < /tmp/dconf-org_mate.ini

# - name: Set panel default-layout using command
#   become_user: "{{ customize_user }}"
#   become: true
#   ansible.builtin.shell:
#     cmd: dbus-launch dconf write /org/mate/panel/general/default-layout "'redmond'"

- name: Wait for server to restart
  reboot:
    reboot_timeout: 3600
    msg: "Reboot initiated by Ansible due to MATE desktop installation"