---
- name: create users with random passwords
  hosts: ansible_vms
  gather_facts: no
  vars:
    mypassword: "{{ lookup('password', '{{ inventory_dir }}/volatile/credentials/{{ item }} length=6') }}"
  tasks:
  - debug:
      msg: random password {{ mypassword }} for user {{ item }}
    loop: "{{ query('lines','cat {{inventory_dir}}/volatile/users.txt') }}"
  - user:
      name: "{{ item }}"
      password: "{{ mypassword | password_hash('sha512') }}"
      update_password: on_create
    loop: "{{ query('lines','cat {{inventory_dir}}/volatile/users.txt') }}"

# ansible-doc -t lookup password
# ansible-doc -t lookup lines
# ansible-doc -t lookup password_hash
# mkdir volatile/credentials
# cat >> volatile/users.txt <<EOF
# anant
# student
# EOF

# ansible-playbook ansible-core-concepts/using-plugins/users-with-password.yaml
