- name: Run Ansible Role
  hosts: all
  remote_user: ansible
  gather_facts: true
  any_errors_fatal: true
  become: true

  # pre_tasks:
  #   - name: Get env variable name
  #     ansible.builtin.debug:
  #       vars: ${{ env.environment }}

  roles:
    - role: github-action-poc-project
      # vars:
      #   minimal_ansible_version: 2.11.0
