---
# tasks file for install-and-configure-guake
- name: Print role name
  debug:
    msg: "Running [{{ role_name }}] role"

- name: Copy [dconf-apps_guake.ini] to {{ ansible_host}}
  become_user: "{{ customize_user }}"
  become: true
  ansible.builtin.copy:
    src: "{{role_path}}/files/dconf-apps_guake.ini"
    dest: /tmp/dconf-apps_guake.ini
    mode: '0644'
  tags: [install, config]

- name: Apply guake settings from config file
  become_user: "{{ customize_user }}"
  become: true
  ansible.builtin.shell:
    cmd: dbus-launch dconf load /apps/guake/ < /tmp/dconf-apps_guake.ini
