---
core_packages:
  - python3-pip
  - dbus-x11
  - dbus
  - tldr
  - dconf-editor
  - guake
  - ubuntu-mate-desktop
  - numlockx
  - python-is-python3
  - curl
  - wget
  #- libasound2
  - flameshot
  - snapd
  - vim
  - nano
  - net-tools

softwares:
  - timeshift
  - vlc
  - gnome-software
  - git
  - slack
  - cpu-checker
  - simplescreenrecorder
  - qbittorrent
  - guvcview # Camera Testing tool
  - stacer
  - cpu-x
  # - netstat
  - notepadqq
  - gparted
  - kdiskmark
  - filezilla
  - remmina
  - htop
  - ffmpeg # Video Decoding tool
  - xrdp
  - ubuntu-restricted-extras

snap_packages:
  - chatgpt-desktop
  - gcompris
  - extreme-tux-racer
  - tuxfight

games:
  - supertux
  - supertuxkart
  - gnome-mines
  - gnome-sudoku

learnings:
  - tuxmath
  - tuxpaint
  - tuxtype
  - scratch
  # - scratchjr # Instructions for scratchjr are present in README.md
  #- gcompris
  - gcompris-qt
  - gimp
  - klettres
  - kolourpaint


packages_to_remove:
  - orca # Screen reader

non_packaged_softwares:
  - name: code
    friendly_name: Visual Studio Code
    url: "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"

  - name: code-insiders
    friendly_name: Visual Studio Code Insiders
    url: "https://code.visualstudio.com/sha/download?build=insider&os=linux-deb-x64"

  - name: zoom
    friendly_name: Zoom
    url: "https://zoom.us/client/latest/zoom_amd64.deb"

  - name: google-chrome
    friendly_name: Google Chrome
    url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"





