---
# - name: check file content
#   ansible.builtin.debug:
#     msg: "{{ lookup('file', '../files/etc_hosts') }}"

# - name: Remove file if exists
#   ansible.builtin.file:
#     path: /tmp/etc_hosts
#     state: absent

# - name: Create file if not exists
#   ansible.builtin.file:
#     path: /tmp/etc_hosts
#     state: touch

- name: Configure /etc/hosts file
  ansible.builtin.blockinfile:
    path: /etc/hosts
    #path: /tmp/etc_hosts
    marker: "##<!-- {mark} ANSIBLE MANAGED BLOCK -->##"
    block: |
      {{ lookup('file', '../files/etc_hosts') }}
