---
- name: Install softwares packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ softwares }}"

- name: Install snap packages
  community.general.snap:
    name: "{{ item }}"
    state: present
  loop: "{{ snap_packages }}"
  when: snap_packages is defined

- name: Check if a reboot is needed for system
  register: reboot_required_file
  stat: path=/var/run/reboot-required

- name: Reboot the system
  ansible.legacy.include_tasks: reboot-system.yml
  when: reboot_required_file.stat.exists


