---
- name: Remove unwanted packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ packages_to_remove }}"

- name: Check if a reboot is needed for system
  register: reboot_required_file
  stat: path=/var/run/reboot-required

- name: Reboot the system
  ansible.legacy.include_tasks: reboot-system.yml
  when: reboot_required_file.stat.exists

