name: Ansible Role Runner

on:
  workflow_dispatch:
    inputs:
      role_folder:
        description: 'Role folder to run'
        required: true
        # default: '<role_folder>'
        default: 'github-action-poc-project'
      clean:
        description: 'Cleanup temp files generated for playbook at end? (y/n)'
        required: true
        default: 'n'

jobs:
  run-ansible-role:
    runs-on: ubuntu
    env:
      ROLE_FOLDER: ${{ github.event.inputs.role_folder }}
      PG_SUPERUSER_PWD: ${{ secrets.PG_SUPERUSER_PWD }}
      PG_APPUSER: ${{ secrets.PG_APPUSER }}
      PG_APPUSER_PWD: ${{ secrets.PG_APPUSER_PWD }}
      CLEANUP: ${{ github.event.inputs.clean }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Copy site.yml & hosts.yml to working directory
        run: |
          ROLE_FOLDER="${{ env.ROLE_FOLDER }}"

          echo "Copying site.yml and hosts.yml from $ROLE_FOLDER"

          cp "$ROLE_FOLDER/site.yml" ./site.yml
          cp "$ROLE_FOLDER/hosts.yml" ./hosts.yml

      - name: Create defaults/creds.yml file
        run: |
          ROLE_FOLDER="${{ env.ROLE_FOLDER }}"

          rm -f $ROLE_FOLDER/defaults/creds.yml
          touch $ROLE_FOLDER/defaults/creds.yml
          echo creds: >> $ROLE_FOLDER/defaults/creds.yml
          echo \ \ PG_SUPERUSER_PWD: $PG_SUPERUSER_PWD >> $ROLE_FOLDER/defaults/creds.yml
          echo \ \ PG_APPUSER: $PG_APPUSER >> $ROLE_FOLDER/defaults/creds.yml
          echo \ \ PG_APPUSER_PWD: $PG_APPUSER_PWD >> $ROLE_FOLDER/defaults/creds.yml

          cat $ROLE_FOLDER/defaults/creds.yml

      - name: Run playbook
        run: |
          echo "Running playbook site.yml with inventory hosts.yml"

          # Run the playbook
          ansible-playbook -i hosts.yml site.yml --extra-vars "role_name=${ROLE_FOLDER}"

      - name: Conditional Cleanup
        if: ${{ env.CLEANUP == 'y' }}
        run: |
          echo "Cleaning up runtime files..."
          rm -f site.yml hosts.yml
          rm -f ${{ env.ROLE_FOLDER }}/defaults/creds.yml
          echo "Cleanup complete!"

      - name: Status of action action
        run: echo "${{ steps.custom.outputs.ansible-status }}"