name: Ansible Playbook Runner

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'which env to run (rolenames)'
        required: true
        default : '<env_name>'

jobs:
  run-ansible-playbook:
    name: Run Ansible Playbook on Ubuntu
    # runs-on: self-hosted
    runs-on: ubuntu
    env:
      environment: ${{ github.event.inputs.environment }}

    # defaults:
    #   run:
    #     working-directory: ansible-core-concepts

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        path: '.github/actions/ansible'

    # - name: Create defaults/creds.yml file
    #   env:
    #     PG_SUPERUSER_PWD: ${{ secrets.PG_SUPERUSER_PWD }}
    #     PG_APPUSER_PWD: ${{ secrets.PG_APPUSER_PWD }}
    #   run: |
    #     rm -f ${{ env.environment }}/defaults/creds.yml
    #     touch ${{ env.environment }}/defaults/creds.yml
    #     echo \ \ PG_SUPERUSER_PWD: $PG_SUPERUSER_PWD >> ${{ env.environment }}/defaults/creds.yml
    #     echo \ \ PG_APPUSER_PWD: $PG_APPUSER_PWD >> ${{ env.environment }}/defaults/creds.yml
    #     cat ${{ env.environment }}/defaults/creds.yml

    # - name: Show Ansible Version
    #   run: ansible --version

    # - name: Copy hosts file
    #   run: "cp ./${{ env.environment }}/hosts.yml ./hosts.yml"

    # - name: Copy site yml
    #   run: "cp ./${{ env.environment }}/site.yml ./site.yml"

    # - name: Deploy postgres
    #   id: custom
    #   uses: ./.github/actions/ansible
    #   with:
    #     input-ansible-key: ${{ secrets.SRE_ANSIBLE_SSH_KEY }}
    #     input-ansible-action: 'run'

    - name: Run Ansible Playbook
      run: |
        ansible-playbook using-roles/roles/poc-role/poc-role.yml -i localhost, -c local

    # - name: remove defaults/creds.yml file
    #   run: |
    #     rm -f ${{ env.environment }}/defaults/creds.yml

    - name: Status of action action
      run: echo "${{ steps.custom.outputs.ansible-status }}"


